version: "2"

run:
  timeout: 1m

linters:
  enable:
    - govet
    - errcheck

  exclusions:
    paths:
      - sample
      - internal/analizer_old
      - internal/analizer_palallel
      - "_test\\.go$"
